version: '3'
services:
    mariadb:
        image: 'mariadb:10.3.9'
        container_name: ${APP_NAME:?err}-mariadb
        restart: 'on-failure'
        ports:
            - '33062:3306'
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
            MYSQL_DATABASE: guestbook
        volumes:
            # - './database:/var/lib/mysql'
            - "./docker/db/:/docker-entrypoint-initdb.d/"
    php:
        # image: 'php:7.2-fpm'
        build:
            context: ./docker
            dockerfile: php.Dockerfile
        container_name: ${APP_NAME:?err}-php
        links:
            - 'mariadb:db'
        volumes:
            - './web:/var/www/html'

    nginx:
        image: 'nginx:1.13.6'
        container_name: ${APP_NAME:?err}-nginx
        ports:
            - '8082:80'
            # - '443:443'
        links:
            - 'php'
        volumes:
            - './web:/var/www/html'
            - './config/nginx:/etc/nginx/conf.d'
